version: '3.8'

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/vendor  # Anonymous volume to prevent host vendor conflicts
    environment:
      APP_ENV: testing
      DB_CONNECTION: sqlite
      DB_DATABASE: ":memory:"
      DISCORD_BOT_TOKEN: test_bot_token
      DISCORD_GUILD_ID: test_guild_id
      PUSHER_APP_ID: test_app_id
      PUSHER_APP_KEY: test_app_key
      PUSHER_APP_SECRET: test_app_secret
      PUSHER_APP_CLUSTER: mt1
      BROADCAST_DRIVER: pusher
    working_dir: /app
    command: ./run-tests.sh
    
  tests-coverage:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/vendor
    environment:
      APP_ENV: testing
      DB_CONNECTION: sqlite
      DB_DATABASE: ":memory:"
      DISCORD_BOT_TOKEN: test_bot_token
      DISCORD_GUILD_ID: test_guild_id
      PUSHER_APP_ID: test_app_id
      PUSHER_APP_KEY: test_app_key
      PUSHER_APP_SECRET: test_app_secret
      PUSHER_APP_CLUSTER: mt1
      BROADCAST_DRIVER: pusher
    working_dir: /app
    command: ./run-tests.sh --coverage
    
  tests-shell:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/vendor
    environment:
      APP_ENV: testing
      DB_CONNECTION: sqlite
      DB_DATABASE: ":memory:"
      DISCORD_BOT_TOKEN: test_bot_token
      DISCORD_GUILD_ID: test_guild_id
    working_dir: /app
    command: /bin/bash
    stdin_open: true
    tty: true
